[package]
name = "simplest-ot"
version = "0.2.0"
authors = ["danzipie <danzipie@gmail.com>"]
edition = "2018"

[dependencies]
curve25519-dalek = { "version" = "4.1.3", "features" = ["rand_core"]  }
ring = "0.16.5"
rand = "0.8"
