[package]
name = "simplest-ot"
version = "0.2.1"
authors = ["danzipie <6286268+danzipie@users.noreply.github.com>"]
edition = "2018"

[dependencies]
curve25519-dalek = { "version" = "4.1.3", "features" = ["rand_core"]  }
ring = "0.17.12"
rand = "0.8"
